from __future__ import annotations

TIMELINE_TOTAL_MS = 20_000

STAGE_SPECS = [
    {
        'stage_id': 'start',
        'title': 'Start',
        'title_zh': '启动',
        'subtitle': 'Initializing generation pipeline and base scene',
        'subtitle_zh': '初始化生成流程与基础场景',
        'timestamp_ms': 0,
        'visible_layers': ['terrain'],
    },
    {
        'stage_id': 'terrain',
        'title': 'Terrain',
        'title_zh': '地形',
        'subtitle': 'Generating terrain elevation and contour baseline',
        'subtitle_zh': '生成地形高程与等高线基底',
        'timestamp_ms': 400,
        'visible_layers': ['terrain', 'contours'],
    },
    {
        'stage_id': 'rivers',
        'title': 'Rivers',
        'title_zh': '河流',
        'subtitle': 'Selecting river courses and shaping river areas',
        'subtitle_zh': '选择河道并构建河流区域',
        'timestamp_ms': 3200,
        'visible_layers': ['terrain', 'rivers', 'river_areas', 'contours'],
    },
    {
        'stage_id': 'hubs',
        'title': 'Hubs',
        'title_zh': '中心点',
        'subtitle': 'Placing urban hubs and hierarchy centers',
        'subtitle_zh': '布设城市中心点与层级中心',
        'timestamp_ms': 5600,
        'visible_layers': ['terrain', 'rivers', 'river_areas', 'contours', 'hubs', 'labels'],
    },
    {
        'stage_id': 'roads',
        'title': 'Roads',
        'title_zh': '道路',
        'subtitle': 'Generating road network and bridge connections',
        'subtitle_zh': '生成道路网络与桥梁连接',
        'timestamp_ms': 7200,
        'visible_layers': ['terrain', 'rivers', 'river_areas', 'contours', 'roads', 'hubs', 'labels'],
    },
    {
        'stage_id': 'artifact',
        'title': 'Artifact',
        'title_zh': '骨架封装',
        'subtitle': 'Packaging core city artifact and previews',
        'subtitle_zh': '封装城市骨架产物与预览数据',
        'timestamp_ms': 13_600,
        'visible_layers': ['terrain', 'rivers', 'river_areas', 'contours', 'roads', 'hubs', 'labels'],
    },
    {
        'stage_id': 'analysis',
        'title': 'Analysis',
        'title_zh': '分析',
        'subtitle': 'Computing suitability, flood risk and resources',
        'subtitle_zh': '计算宜居性、洪涝风险与资源分布',
        'timestamp_ms': 14_400,
        'visible_layers': ['terrain', 'rivers', 'river_areas', 'contours', 'analysis_heatmaps', 'resources'],
    },
    {
        'stage_id': 'traffic',
        'title': 'Traffic',
        'title_zh': '交通模拟',
        'subtitle': 'Assigning OD flows and congestion preview',
        'subtitle_zh': 'OD流量分配与拥堵预览',
        'timestamp_ms': 15_600,
        'visible_layers': ['terrain', 'rivers', 'river_areas', 'contours', 'roads', 'hubs', 'traffic_heat'],
    },
    {
        'stage_id': 'buildings',
        'title': 'Buildings',
        'title_zh': '建筑预览',
        'subtitle': 'Generating building footprints and green zones',
        'subtitle_zh': '生成建筑轮廓与绿地区域预览',
        'timestamp_ms': 16_400,
        'visible_layers': ['terrain', 'rivers', 'river_areas', 'contours', 'roads', 'hubs', 'labels', 'buildings', 'green_zones'],
    },
    {
        'stage_id': 'parcels',
        'title': 'Parcels',
        'title_zh': '地块/宗地',
        'subtitle': 'Extracting blocks, parcels and pedestrian paths',
        'subtitle_zh': '提取街区、宗地与步行路径',
        'timestamp_ms': 18_000,
        'visible_layers': ['terrain', 'rivers', 'river_areas', 'contours', 'roads', 'hubs', 'labels', 'pedestrian_paths', 'blocks', 'parcels'],
    },
    {
        'stage_id': 'stages',
        'title': 'Stages',
        'title_zh': '阶段组装',
        'subtitle': 'Assembling timeline stages and composite preview',
        'subtitle_zh': '组装阶段快照与合成预览',
        'timestamp_ms': 19_200,
        'visible_layers': [
            'terrain',
            'rivers',
            'river_areas',
            'contours',
            'roads',
            'hubs',
            'labels',
            'pedestrian_paths',
            'blocks',
            'parcels',
            'buildings',
            'green_zones',
        ],
    },
    {
        'stage_id': 'done',
        'title': 'Done',
        'title_zh': '完成',
        'subtitle': 'Generation complete with final city preview',
        'subtitle_zh': '生成完成并输出最终城市预览',
        'timestamp_ms': TIMELINE_TOTAL_MS,
        'visible_layers': [
            'terrain',
            'rivers',
            'river_areas',
            'contours',
            'roads',
            'hubs',
            'labels',
            'pedestrian_paths',
            'blocks',
            'parcels',
            'buildings',
            'green_zones',
        ],
    },
]

STAGE_IDS = [str(spec['stage_id']) for spec in STAGE_SPECS]
